// <auto-generated />
using System;
using System.Collections.Generic;
using Backend_Almacen.Domain.Enums;
using Backend_Almacen.Infrastructure.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend_Almacen.Infrastructure.Persistencia.Migraciones
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260923183522_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "accion_auditoria", new[] { "borrar", "crear", "descargar_reporte", "editar" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "estado_mensaje_whatsapp", new[] { "bloqueado_lista_blanca", "enviado", "error" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "estado_pedido", new[] { "aprobado", "asignado", "en_camino", "entregado", "expirado", "pendiente", "rechazado" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "metodo_pago", new[] { "binance", "pago_movil", "transferencia" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "moneda_pago", new[] { "USDT", "VES" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "rol_usuario", new[] { "cliente", "repartidor", "superadmin", "ventas" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "tipo_movimiento_inventario", new[] { "ajuste", "liberacion", "reposicion", "reserva", "venta" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "tipo_notificacion", new[] { "pedido_nuevo", "pedido_por_expirar", "stock_agotado" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend_Almacen.Domain.Entidades.Auditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<AccionAuditoria>("Accion")
                        .HasColumnType("accion_auditoria")
                        .HasColumnName("accion");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DatosAntes")
                        .HasColumnType("jsonb")
                        .HasColumnName("datos_antes");

                    b.Property<string>("DatosDespues")
                        .HasColumnType("jsonb")
                        .HasColumnName("datos_despues");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("entidad");

                    b.Property<Guid?>("EntidadId")
                        .HasColumnType("uuid")
                        .HasColumnName("entidad_id");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_auditoria");

                    b.HasIndex("CreadoEn")
                        .HasDatabaseName("ix_auditoria_creado_en");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_auditoria_usuario_id");

                    b.HasIndex("Entidad", "EntidadId")
                        .HasDatabaseName("ix_auditoria_entidad_entidad_id");

                    b.ToTable("auditoria", (string)null);
                });

            modelBuilder.Entity("Backend_Almacen.Domain.Entidades.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_categorias");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ix_categorias_nombre");

                    b.ToTable("categorias", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c1000000-0000-4000-8000-000000000001"),
                            Nombre = "Víveres"
                        },
                        new
                        {
                            Id = new Guid("c1000000-0000-4000-8000-000000000002"),
                            Nombre = "Lácteos y huevos"
                        },
                        new
                        {
                            Id = new Guid("c1000000-0000-4000-8000-000000000003"),
                            Nombre = "Bebidas"
                        },
                        new
                        {
                            Id = new Guid("c1000000-0000-4000-8000-000000000004"),
                            Nombre = "Limpieza del hogar"
                        });
                });

            modelBuilder.Entity("Backend_Almacen.Domain.Entidades.Configuracion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DatosPagoMovil")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("datos_pago_movil");

                    b.Property<string>("DatosTransferencia")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("datos_transferencia");

                    b.Property<int>("HorasExpiracion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(5)
                        .HasColumnName("horas_expiracion");

                    b.Property<string>("NumeroSoporte")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("numero_soporte");

                    b.PrimitiveCollection<List<string>>("NumerosPrueba")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("numeros_prueba")
                        .HasDefaultValueSql("'{}'");

                    b.Property<decimal?>("TasaBsUsd")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("tasa_bs_usd");

                    b.Property<string>("WalletBinance")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("wallet_binance");

                    b.HasKey("Id")
                        .HasName("pk_configuracion");

                    b.ToTable("configuracion", null, t =>
                        {
                            t.HasCheckConstraint("ck_configuracion_horas_expiracion", "horas_expiracion > 0");

                            t.HasCheckConstraint("ck_configuracion_una_fila", "id = '00000000-0000-0000-0000-000000000001'");
                        });
                });

            modelBuilder.Entity("Backend_Almacen.Domain.Entidades.HistorialEstadoPedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<EstadoPedido?>("EstadoAnterior")
                        .HasColumnType("estado_pedido")
                        .HasColumnName("estado_anterior");

                    b.Property<EstadoPedido>("EstadoNuevo")
                        .HasColumnType("estado_pedido")
                        .HasColumnName("estado_nuevo");

                    b.Property<Guid>("PedidoId")
                        .HasColumnType("uuid")
                        .HasColumnName("pedido_id");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_historial_estados_pedido");

                    b.HasIndex("PedidoId")
                        .HasDatabaseName("ix_historial_estados_pedido_pedido_id");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_historial_estados_pedido_usuario_id");

                    b.ToTable("historial_estados_pedido", (string)null);
                });

            modelBuilder.Entity("Backend_Almacen.Domain.Entidades.HistorialTasa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("Tasa")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("tasa");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_historial_tasas");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_historial_tasas_usuario_id");

                    b.ToTable("historial_tasas", null, t =>
                        {
                            t.HasCheckConstraint("ck_historial_tasas_tasa", "tasa > 0");
                        });
                });

            modelBuilder.Entity("Backend_Almacen.Domain.Entidades.MensajeWhatsapp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error");

                    b.Property<EstadoMensajeWhatsapp>("Estado")
                        .HasColumnType("estado_mensaje_whatsapp")
                        .HasColumnName("estado");

                    b.Property<Guid>("PedidoId")
                        .HasColumnType("uuid")
                        .HasColumnName("pedido_id");

                    b.Property<string>("Plantilla")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("plantilla");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("texto");

                    b.HasKey("Id")
                        .HasName("pk_mensajes_whatsapp");

                    b.HasIndex("PedidoId")
                        .HasDatabaseName("ix_mensajes_whatsapp_pedido_id");

                    b.ToTable("mensajes_whatsapp", (string)null);
                });

            modelBuilder.Entity("Backend_Almacen.Domain.Entidades.MovimientoInventario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("DisponibleAntes")
                        .HasColumnType("integer")
                        .HasColumnName("disponible_antes");

                    b.Property<int>("DisponibleDespues")
                        .HasColumnType("integer")
                        .HasColumnName("disponible_despues");

                    b.Property<Guid?>("PedidoId")
                        .HasColumnType("uuid")
                        .HasColumnName("pedido_id");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid")
                        .HasColumnName("producto_id");

                    b.Property<TipoMovimientoInventario>("Tipo")
                        .HasColumnType("tipo_movimiento_inventario")
                        .HasColumnName("tipo");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_movimientos_inventario");

                    b.HasIndex("PedidoId")
                        .HasDatabaseName("ix_movimientos_inventario_pedido_id");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_movimientos_inventario_usuario_id");

                    b.HasIndex("ProductoId", "CreadoEn")
                        .HasDatabaseName("ix_movimientos_inventario_producto_id_creado_en");

                    b.ToTable("movimientos_inventario", (string)null);
                });

            modelBuilder.Entity("Backend_Almacen.Domain.Entidades.Notificacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("Leida")
                        .HasColumnType("boolean")
                        .HasColumnName("leida");

                    b.Property<Guid?>("PedidoId")
                        .HasColumnType("uuid")
                        .HasColumnName("pedido_id");

                    b.Property<Guid?>("ProductoId")
                        .HasColumnType("uuid")
                        .HasColumnName("producto_id");

                    b.Property<TipoNotificacion>("Tipo")
                        .HasColumnType("tipo_notificacion")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("pk_notificaciones");

                    b.HasIndex("PedidoId")
                        .HasDatabaseName("ix_notificaciones_pedido_id");

                    b.HasIndex("ProductoId")
                        .HasDatabaseName("ix_notificaciones_producto_id");

                    b.HasIndex("Leida", "CreadoEn")
                        .HasDatabaseName("ix_notificaciones_leida_creado_en");

                    b.ToTable("notificaciones", null, t =>
                        {
                            t.HasCheckConstraint("ck_notificaciones_referencia", "producto_id IS NOT NULL OR pedido_id IS NOT NULL");
                        });
                });

            modelBuilder.Entity("Backend_Almacen.Domain.Entidades.Pedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AsignadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("asignado_en");

                    b.Property<string>("CapturaUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("captura_url");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DireccionTexto")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("direccion_texto");

                    b.Property<DateTime?>("EnCaminoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("en_camino_en");

                    b.Property<DateTime?>("EntregadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("entregado_en");

                    b.Property<EstadoPedido>("Estado")
                        .HasColumnType("estado_pedido")
                        .HasColumnName("estado");

                    b.Property<DateTime>("ExpiraEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_en");

                    b.Property<double?>("Latitud")
                        .HasColumnType("double precision")
                        .HasColumnName("latitud");

                    b.Property<double?>("Longitud")
                        .HasColumnType("double precision")
                        .HasColumnName("longitud");

                    b.Property<MetodoPago>("MetodoPago")
                        .HasColumnType("metodo_pago")
                        .HasColumnName("metodo_pago");

                    b.Property<MonedaPago>("MonedaPago")
                        .HasColumnType("moneda_pago")
                        .HasColumnName("moneda_pago");

                    b.Property<string>("MotivoRechazo")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("motivo_rechazo");

                    b.Property<int>("Numero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("numero");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Numero"));

                    b.Property<string>("ReferenciaPago")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("referencia_pago");

                    b.Property<Guid?>("RepartidorId")
                        .HasColumnType("uuid")
                        .HasColumnName("repartidor_id");

                    b.Property<DateTime?>("RevisadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revisado_en");

                    b.Property<Guid?>("RevisadoPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("revisado_por");

                    b.Property<decimal>("TasaCambio")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("tasa_cambio");

                    b.Property<string>("TelefonoContacto")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono_contacto");

                    b.Property<decimal>("TotalBs")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_bs");

                    b.Property<decimal>("TotalUsd")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_usd");

                    b.Property<Guid>("ZonaId")
                        .HasColumnType("uuid")
                        .HasColumnName("zona_id");

                    b.HasKey("Id")
                        .HasName("pk_pedidos");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("ix_pedidos_cliente_id");

                    b.HasIndex("Numero")
                        .IsUnique()
                        .HasDatabaseName("ix_pedidos_numero");

                    b.HasIndex("RepartidorId")
                        .HasDatabaseName("ix_pedidos_repartidor_id");

                    b.HasIndex("RevisadoPorId")
                        .HasDatabaseName("ix_pedidos_revisado_por_id");

                    b.HasIndex("ZonaId")
                        .HasDatabaseName("ix_pedidos_zona_id");

                    b.HasIndex("Estado", "CreadoEn")
                        .HasDatabaseName("ix_pedidos_estado_creado_en");

                    b.HasIndex("Estado", "ExpiraEn")
                        .HasDatabaseName("ix_pedidos_estado_expira_en");

                    b.ToTable("pedidos", null, t =>
                        {
                            t.HasCheckConstraint("ck_pedidos_totales", "total_usd >= 0 AND total_bs >= 0 AND tasa_cambio > 0");
                        });
                });

            modelBuilder.Entity("Backend_Almacen.Domain.Entidades.PedidoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uuid")
                        .HasColumnName("categoria_id");

                    b.Property<Guid>("PedidoId")
                        .HasColumnType("uuid")
                        .HasColumnName("pedido_id");

                    b.Property<decimal>("PrecioBs")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("precio_bs");

                    b.Property<decimal>("PrecioUsd")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("precio_usd");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid")
                        .HasColumnName("producto_id");

                    b.HasKey("Id")
                        .HasName("pk_pedido_items");

                    b.HasIndex("CategoriaId")
                        .HasDatabaseName("ix_pedido_items_categoria_id");

                    b.HasIndex("PedidoId")
                        .HasDatabaseName("ix_pedido_items_pedido_id");

                    b.HasIndex("ProductoId")
                        .HasDatabaseName("ix_pedido_items_producto_id");

                    b.ToTable("pedido_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_pedido_items_cantidad", "cantidad > 0");
                        });
                });

            modelBuilder.Entity("Backend_Almacen.Domain.Entidades.Producto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uuid")
                        .HasColumnName("categoria_id");

                    b.Property<string>("CodigoSku")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("codigo_sku");

                    b.Property<decimal>("CostoUsd")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("costo_usd");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreadoPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creado_por");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("descripcion");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("imagen_url");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("PrecioUsd")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("precio_usd");

                    b.Property<int>("StockDisponible")
                        .HasColumnType("integer")
                        .HasColumnName("stock_disponible");

                    b.Property<int>("StockReservado")
                        .HasColumnType("integer")
                        .HasColumnName("stock_reservado");

                    b.HasKey("Id")
                        .HasName("pk_productos");

                    b.HasIndex("CategoriaId")
                        .HasDatabaseName("ix_productos_categoria_id");

                    b.HasIndex("CodigoSku")
                        .IsUnique()
                        .HasDatabaseName("ix_productos_codigo_sku");

                    b.HasIndex("CreadoPorId")
                        .HasDatabaseName("ix_productos_creado_por_id");

                    b.HasIndex("Activo", "StockDisponible")
                        .HasDatabaseName("ix_productos_activo_stock_disponible");

                    b.ToTable("productos", null, t =>
                        {
                            t.HasCheckConstraint("ck_productos_costo_usd", "costo_usd >= 0");

                            t.HasCheckConstraint("ck_productos_precio_usd", "precio_usd >= 0");

                            t.HasCheckConstraint("ck_productos_stock_disponible", "stock_disponible >= 0");

                            t.HasCheckConstraint("ck_productos_stock_reservado", "stock_reservado >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1000000-0000-4000-8000-000000000001"),
                            Activo = true,
                            CategoriaId = new Guid("c1000000-0000-4000-8000-000000000001"),
                            CodigoSku = "VIV-0001",
                            CostoUsd = 1.05m,
                            CreadoEn = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "Harina blanca para arepas.",
                            Nombre = "Harina de maíz precocida 1 kg",
                            PrecioUsd = 1.35m,
                            StockDisponible = 120,
                            StockReservado = 0
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-4000-8000-000000000002"),
                            Activo = true,
                            CategoriaId = new Guid("c1000000-0000-4000-8000-000000000001"),
                            CodigoSku = "VIV-0002",
                            CostoUsd = 0.92m,
                            CreadoEn = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "Arroz de grano largo.",
                            Nombre = "Arroz blanco tipo I 1 kg",
                            PrecioUsd = 1.20m,
                            StockDisponible = 150,
                            StockReservado = 0
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-4000-8000-000000000003"),
                            Activo = true,
                            CategoriaId = new Guid("c1000000-0000-4000-8000-000000000001"),
                            CodigoSku = "VIV-0003",
                            CostoUsd = 1.18m,
                            CreadoEn = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "Espagueti de sémola de trigo.",
                            Nombre = "Pasta larga 1 kg",
                            PrecioUsd = 1.60m,
                            StockDisponible = 90,
                            StockReservado = 0
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-4000-8000-000000000004"),
                            Activo = true,
                            CategoriaId = new Guid("c1000000-0000-4000-8000-000000000001"),
                            CodigoSku = "VIV-0004",
                            CostoUsd = 2.55m,
                            CreadoEn = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "Aceite de soya.",
                            Nombre = "Aceite vegetal 1 L",
                            PrecioUsd = 3.20m,
                            StockDisponible = 60,
                            StockReservado = 0
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-4000-8000-000000000005"),
                            Activo = true,
                            CategoriaId = new Guid("c1000000-0000-4000-8000-000000000002"),
                            CodigoSku = "LAC-0001",
                            CostoUsd = 1.40m,
                            CreadoEn = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "Leche de larga duración.",
                            Nombre = "Leche completa UHT 1 L",
                            PrecioUsd = 1.85m,
                            StockDisponible = 80,
                            StockReservado = 0
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-4000-8000-000000000006"),
                            Activo = true,
                            CategoriaId = new Guid("c1000000-0000-4000-8000-000000000002"),
                            CodigoSku = "LAC-0002",
                            CostoUsd = 5.10m,
                            CreadoEn = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "Queso llanero.",
                            Nombre = "Queso blanco duro 1 kg",
                            PrecioUsd = 6.50m,
                            StockDisponible = 25,
                            StockReservado = 0
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-4000-8000-000000000007"),
                            Activo = true,
                            CategoriaId = new Guid("c1000000-0000-4000-8000-000000000002"),
                            CodigoSku = "LAC-0003",
                            CostoUsd = 4.70m,
                            CreadoEn = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "Huevos blancos tamaño AA.",
                            Nombre = "Huevos cartón 30 unidades",
                            PrecioUsd = 5.90m,
                            StockDisponible = 40,
                            StockReservado = 0
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-4000-8000-000000000008"),
                            Activo = true,
                            CategoriaId = new Guid("c1000000-0000-4000-8000-000000000003"),
                            CodigoSku = "BEB-0001",
                            CostoUsd = 3.75m,
                            CreadoEn = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "Tueste medio.",
                            Nombre = "Café molido 500 g",
                            PrecioUsd = 4.80m,
                            StockDisponible = 50,
                            StockReservado = 0
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-4000-8000-000000000009"),
                            Activo = true,
                            CategoriaId = new Guid("c1000000-0000-4000-8000-000000000003"),
                            CodigoSku = "BEB-0002",
                            CostoUsd = 1.55m,
                            CreadoEn = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "Bebida gaseosa.",
                            Nombre = "Refresco de cola 2 L",
                            PrecioUsd = 2.10m,
                            StockDisponible = 70,
                            StockReservado = 0
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-4000-8000-000000000010"),
                            Activo = true,
                            CategoriaId = new Guid("c1000000-0000-4000-8000-000000000004"),
                            CodigoSku = "LIM-0001",
                            CostoUsd = 2.60m,
                            CreadoEn = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "Para ropa blanca y de color.",
                            Nombre = "Detergente en polvo 1 kg",
                            PrecioUsd = 3.40m,
                            StockDisponible = 45,
                            StockReservado = 0
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-4000-8000-000000000011"),
                            Activo = true,
                            CategoriaId = new Guid("c1000000-0000-4000-8000-000000000004"),
                            CodigoSku = "LIM-0002",
                            CostoUsd = 0.90m,
                            CreadoEn = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "Blanqueador y desinfectante.",
                            Nombre = "Cloro 1 L",
                            PrecioUsd = 1.25m,
                            StockDisponible = 65,
                            StockReservado = 0
                        });
                });

            modelBuilder.Entity("Backend_Almacen.Domain.Entidades.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("GoogleId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("google_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("password_hash");

                    b.Property<RolUsuario>("Rol")
                        .HasColumnType("rol_usuario")
                        .HasColumnName("rol");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_email");

                    b.HasIndex("GoogleId")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_google_id");

                    b.ToTable("usuarios", null, t =>
                        {
                            t.HasCheckConstraint("ck_usuarios_credenciales", "(rol = 'cliente' AND google_id IS NOT NULL) OR (rol <> 'cliente' AND password_hash IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Backend_Almacen.Domain.Entidades.Zona", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean")
                        .HasColumnName("activa");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_zonas");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ix_zonas_nombre");

                    b.ToTable("zonas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e1000000-0000-4000-8000-000000000001"),
                            Activa = true,
                            Nombre = "Centro"
                        },
                        new
                        {
                            Id = new Guid("e1000000-0000-4000-8000-000000000002"),
                            Activa = true,
                            Nombre = "Barrio Obrero"
                        },
                        new
                        {
                            Id = new Guid("e1000000-0000-4000-8000-000000000003"),
                            Activa = true,
                            Nombre = "Pueblo Nuevo"
                        },
                        new
                        {
                            Id = new Guid("e1000000-0000-4000-8000-000000000004"),
                            Activa = true,
                            Nombre = "La Concordia"
                        },
                        new
                        {
                            Id = new Guid("e1000000-0000-4000-8000-000000000005"),
                            Activa = true,
                            Nombre = "Santa Teresa"
                        });
                });

            modelBuilder.Entity("Backend_Almacen.Domain.Entidades.Auditoria", b =>
                {
                    b.HasOne("Backend_Almacen.Domain.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_auditoria_usuarios_usuario_id");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Backend_Almacen.Domain.Entidades.HistorialEstadoPedido", b =>
                {
                    b.HasOne("Backend_Almacen.Domain.Entidades.Pedido", "Pedido")
                        .WithMany("HistorialEstados")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_historial_estados_pedido_pedidos_pedido_id");

                    b.HasOne("Backend_Almacen.Domain.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_historial_estados_pedido_usuarios_usuario_id");

                    b.Navigation("Pedido");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Backend_Almacen.Domain.Entidades.HistorialTasa", b =>
                {
                    b.HasOne("Backend_Almacen.Domain.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_historial_tasas_usuarios_usuario_id");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Backend_Almacen.Domain.Entidades.MensajeWhatsapp", b =>
                {
                    b.HasOne("Backend_Almacen.Domain.Entidades.Pedido", "Pedido")
                        .WithMany()
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_mensajes_whatsapp_pedidos_pedido_id");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("Backend_Almacen.Domain.Entidades.MovimientoInventario", b =>
                {
                    b.HasOne("Backend_Almacen.Domain.Entidades.Pedido", "Pedido")
                        .WithMany()
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_movimientos_inventario_pedidos_pedido_id");

                    b.HasOne("Backend_Almacen.Domain.Entidades.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_movimientos_inventario_productos_producto_id");

                    b.HasOne("Backend_Almacen.Domain.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_movimientos_inventario_usuarios_usuario_id");

                    b.Navigation("Pedido");

                    b.Navigation("Producto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Backend_Almacen.Domain.Entidades.Notificacion", b =>
                {
                    b.HasOne("Backend_Almacen.Domain.Entidades.Pedido", "Pedido")
                        .WithMany()
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_notificaciones_pedidos_pedido_id");

                    b.HasOne("Backend_Almacen.Domain.Entidades.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_notificaciones_productos_producto_id");

                    b.Navigation("Pedido");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Backend_Almacen.Domain.Entidades.Pedido", b =>
                {
                    b.HasOne("Backend_Almacen.Domain.Entidades.Usuario", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pedidos_usuarios_cliente_id");

                    b.HasOne("Backend_Almacen.Domain.Entidades.Usuario", "Repartidor")
                        .WithMany()
                        .HasForeignKey("RepartidorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_pedidos_usuarios_repartidor_id");

                    b.HasOne("Backend_Almacen.Domain.Entidades.Usuario", "RevisadoPor")
                        .WithMany()
                        .HasForeignKey("RevisadoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_pedidos_usuarios_revisado_por_id");

                    b.HasOne("Backend_Almacen.Domain.Entidades.Zona", "Zona")
                        .WithMany()
                        .HasForeignKey("ZonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pedidos_zonas_zona_id");

                    b.Navigation("Cliente");

                    b.Navigation("Repartidor");

                    b.Navigation("RevisadoPor");

                    b.Navigation("Zona");
                });

            modelBuilder.Entity("Backend_Almacen.Domain.Entidades.PedidoItem", b =>
                {
                    b.HasOne("Backend_Almacen.Domain.Entidades.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pedido_items_categorias_categoria_id");

                    b.HasOne("Backend_Almacen.Domain.Entidades.Pedido", "Pedido")
                        .WithMany("Items")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pedido_items_pedidos_pedido_id");

                    b.HasOne("Backend_Almacen.Domain.Entidades.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pedido_items_productos_producto_id");

                    b.Navigation("Categoria");

                    b.Navigation("Pedido");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Backend_Almacen.Domain.Entidades.Producto", b =>
                {
                    b.HasOne("Backend_Almacen.Domain.Entidades.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_productos_categorias_categoria_id");

                    b.HasOne("Backend_Almacen.Domain.Entidades.Usuario", "CreadoPor")
                        .WithMany()
                        .HasForeignKey("CreadoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_productos_usuarios_creado_por_id");

                    b.Navigation("Categoria");

                    b.Navigation("CreadoPor");
                });

            modelBuilder.Entity("Backend_Almacen.Domain.Entidades.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("Backend_Almacen.Domain.Entidades.Pedido", b =>
                {
                    b.Navigation("HistorialEstados");

                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
