// <auto-generated />
using System;
using System.Collections.Generic;
using Backend_Almacen.Data;
using Backend_Almacen.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend_Almacen.Data.Migrations
{
    [DbContext(typeof(AlmacenDbContext))]
    [Migration("20260923031154_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "accion_auditoria", new[] { "borrar", "crear", "descargar_reporte", "editar" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "estado_mensaje_whatsapp", new[] { "bloqueado_lista_blanca", "enviado", "error" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "estado_pedido", new[] { "aprobado", "asignado", "en_camino", "entregado", "expirado", "pendiente", "rechazado" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "metodo_pago", new[] { "binance", "pago_movil", "transferencia" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "moneda_pago", new[] { "USDT", "VES" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "rol_usuario", new[] { "cliente", "repartidor", "superadmin", "ventas" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "tipo_movimiento_inventario", new[] { "ajuste", "liberacion", "reposicion", "reserva", "venta" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "tipo_notificacion", new[] { "pedido_nuevo", "pedido_por_expirar", "stock_agotado" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend_Almacen.Models.Auditoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<AccionAuditoria>("Accion")
                        .HasColumnType("accion_auditoria")
                        .HasColumnName("accion");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DatosAntes")
                        .HasColumnType("jsonb")
                        .HasColumnName("datos_antes");

                    b.Property<string>("DatosDespues")
                        .HasColumnType("jsonb")
                        .HasColumnName("datos_despues");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("entidad");

                    b.Property<int?>("EntidadId")
                        .HasColumnType("integer")
                        .HasColumnName("entidad_id");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_auditoria");

                    b.HasIndex("CreadoEn")
                        .HasDatabaseName("ix_auditoria_creado_en");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_auditoria_usuario_id");

                    b.HasIndex("Entidad", "EntidadId")
                        .HasDatabaseName("ix_auditoria_entidad_entidad_id");

                    b.ToTable("auditoria", (string)null);
                });

            modelBuilder.Entity("Backend_Almacen.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_categorias");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ix_categorias_nombre");

                    b.ToTable("categorias", (string)null);
                });

            modelBuilder.Entity("Backend_Almacen.Models.Configuracion", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("DatosPagoMovil")
                        .HasColumnType("text")
                        .HasColumnName("datos_pago_movil");

                    b.Property<string>("DatosTransferencia")
                        .HasColumnType("text")
                        .HasColumnName("datos_transferencia");

                    b.Property<int>("HorasExpiracion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(5)
                        .HasColumnName("horas_expiracion");

                    b.Property<string>("NumeroSoporte")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("numero_soporte");

                    b.PrimitiveCollection<List<string>>("NumerosPrueba")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("numeros_prueba")
                        .HasDefaultValueSql("'{}'");

                    b.Property<decimal?>("TasaBsUsd")
                        .HasPrecision(14, 4)
                        .HasColumnType("numeric(14,4)")
                        .HasColumnName("tasa_bs_usd");

                    b.Property<string>("WalletBinance")
                        .HasColumnType("text")
                        .HasColumnName("wallet_binance");

                    b.HasKey("Id")
                        .HasName("pk_configuracion");

                    b.ToTable("configuracion", null, t =>
                        {
                            t.HasCheckConstraint("ck_configuracion_horas_expiracion", "horas_expiracion > 0");

                            t.HasCheckConstraint("ck_configuracion_una_fila", "id = 1");
                        });
                });

            modelBuilder.Entity("Backend_Almacen.Models.HistorialEstadoPedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<EstadoPedido?>("EstadoAnterior")
                        .HasColumnType("estado_pedido")
                        .HasColumnName("estado_anterior");

                    b.Property<EstadoPedido>("EstadoNuevo")
                        .HasColumnType("estado_pedido")
                        .HasColumnName("estado_nuevo");

                    b.Property<int>("PedidoId")
                        .HasColumnType("integer")
                        .HasColumnName("pedido_id");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_historial_estados_pedido");

                    b.HasIndex("PedidoId")
                        .HasDatabaseName("ix_historial_estados_pedido_pedido_id");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_historial_estados_pedido_usuario_id");

                    b.ToTable("historial_estados_pedido", (string)null);
                });

            modelBuilder.Entity("Backend_Almacen.Models.HistorialTasa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("Tasa")
                        .HasPrecision(14, 4)
                        .HasColumnType("numeric(14,4)")
                        .HasColumnName("tasa");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_historial_tasas");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_historial_tasas_usuario_id");

                    b.ToTable("historial_tasas", null, t =>
                        {
                            t.HasCheckConstraint("ck_historial_tasas_tasa", "tasa > 0");
                        });
                });

            modelBuilder.Entity("Backend_Almacen.Models.MensajeWhatsapp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<EstadoMensajeWhatsapp>("Estado")
                        .HasColumnType("estado_mensaje_whatsapp")
                        .HasColumnName("estado");

                    b.Property<int>("PedidoId")
                        .HasColumnType("integer")
                        .HasColumnName("pedido_id");

                    b.Property<string>("Plantilla")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("plantilla");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("texto");

                    b.HasKey("Id")
                        .HasName("pk_mensajes_whatsapp");

                    b.HasIndex("PedidoId")
                        .HasDatabaseName("ix_mensajes_whatsapp_pedido_id");

                    b.ToTable("mensajes_whatsapp", (string)null);
                });

            modelBuilder.Entity("Backend_Almacen.Models.MovimientoInventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("DisponibleAntes")
                        .HasColumnType("integer")
                        .HasColumnName("disponible_antes");

                    b.Property<int>("DisponibleDespues")
                        .HasColumnType("integer")
                        .HasColumnName("disponible_despues");

                    b.Property<int?>("PedidoId")
                        .HasColumnType("integer")
                        .HasColumnName("pedido_id");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer")
                        .HasColumnName("producto_id");

                    b.Property<TipoMovimientoInventario>("Tipo")
                        .HasColumnType("tipo_movimiento_inventario")
                        .HasColumnName("tipo");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_movimientos_inventario");

                    b.HasIndex("PedidoId")
                        .HasDatabaseName("ix_movimientos_inventario_pedido_id");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_movimientos_inventario_usuario_id");

                    b.HasIndex("ProductoId", "CreadoEn")
                        .HasDatabaseName("ix_movimientos_inventario_producto_id_creado_en");

                    b.ToTable("movimientos_inventario", (string)null);
                });

            modelBuilder.Entity("Backend_Almacen.Models.Notificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("Leida")
                        .HasColumnType("boolean")
                        .HasColumnName("leida");

                    b.Property<int?>("PedidoId")
                        .HasColumnType("integer")
                        .HasColumnName("pedido_id");

                    b.Property<int?>("ProductoId")
                        .HasColumnType("integer")
                        .HasColumnName("producto_id");

                    b.Property<TipoNotificacion>("Tipo")
                        .HasColumnType("tipo_notificacion")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("pk_notificaciones");

                    b.HasIndex("PedidoId")
                        .HasDatabaseName("ix_notificaciones_pedido_id");

                    b.HasIndex("ProductoId")
                        .HasDatabaseName("ix_notificaciones_producto_id");

                    b.ToTable("notificaciones", null, t =>
                        {
                            t.HasCheckConstraint("ck_notificaciones_referencia", "producto_id IS NOT NULL OR pedido_id IS NOT NULL");
                        });
                });

            modelBuilder.Entity("Backend_Almacen.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AsignadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("asignado_en");

                    b.Property<string>("CapturaUrl")
                        .HasColumnType("text")
                        .HasColumnName("captura_url");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("cliente_id");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DireccionTexto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("direccion_texto");

                    b.Property<DateTime?>("EnCaminoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("en_camino_en");

                    b.Property<DateTime?>("EntregadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("entregado_en");

                    b.Property<EstadoPedido>("Estado")
                        .HasColumnType("estado_pedido")
                        .HasColumnName("estado");

                    b.Property<DateTime>("ExpiraEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_en");

                    b.Property<double?>("Latitud")
                        .HasColumnType("double precision")
                        .HasColumnName("latitud");

                    b.Property<double?>("Longitud")
                        .HasColumnType("double precision")
                        .HasColumnName("longitud");

                    b.Property<MetodoPago>("MetodoPago")
                        .HasColumnType("metodo_pago")
                        .HasColumnName("metodo_pago");

                    b.Property<MonedaPago>("MonedaPago")
                        .HasColumnType("moneda_pago")
                        .HasColumnName("moneda_pago");

                    b.Property<string>("MotivoRechazo")
                        .HasColumnType("text")
                        .HasColumnName("motivo_rechazo");

                    b.Property<string>("ReferenciaPago")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("referencia_pago");

                    b.Property<int?>("RepartidorId")
                        .HasColumnType("integer")
                        .HasColumnName("repartidor_id");

                    b.Property<DateTime?>("RevisadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revisado_en");

                    b.Property<int?>("RevisadoPorId")
                        .HasColumnType("integer")
                        .HasColumnName("revisado_por");

                    b.Property<decimal>("TasaCambio")
                        .HasPrecision(14, 4)
                        .HasColumnType("numeric(14,4)")
                        .HasColumnName("tasa_cambio");

                    b.Property<string>("TelefonoContacto")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono_contacto");

                    b.Property<decimal>("TotalBs")
                        .HasPrecision(16, 2)
                        .HasColumnType("numeric(16,2)")
                        .HasColumnName("total_bs");

                    b.Property<decimal>("TotalUsd")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total_usd");

                    b.Property<int>("ZonaId")
                        .HasColumnType("integer")
                        .HasColumnName("zona_id");

                    b.HasKey("Id")
                        .HasName("pk_pedidos");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("ix_pedidos_cliente_id");

                    b.HasIndex("RepartidorId")
                        .HasDatabaseName("ix_pedidos_repartidor_id");

                    b.HasIndex("RevisadoPorId")
                        .HasDatabaseName("ix_pedidos_revisado_por_id");

                    b.HasIndex("ZonaId")
                        .HasDatabaseName("ix_pedidos_zona_id");

                    b.HasIndex("Estado", "CreadoEn")
                        .HasDatabaseName("ix_pedidos_estado_creado_en");

                    b.HasIndex("Estado", "ExpiraEn")
                        .HasDatabaseName("ix_pedidos_estado_expira_en");

                    b.ToTable("pedidos", null, t =>
                        {
                            t.HasCheckConstraint("ck_pedidos_totales", "total_usd >= 0 AND total_bs >= 0 AND tasa_cambio > 0");
                        });
                });

            modelBuilder.Entity("Backend_Almacen.Models.PedidoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer")
                        .HasColumnName("categoria_id");

                    b.Property<int>("PedidoId")
                        .HasColumnType("integer")
                        .HasColumnName("pedido_id");

                    b.Property<decimal>("PrecioBs")
                        .HasPrecision(16, 2)
                        .HasColumnType("numeric(16,2)")
                        .HasColumnName("precio_bs");

                    b.Property<decimal>("PrecioUsd")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("precio_usd");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer")
                        .HasColumnName("producto_id");

                    b.HasKey("Id")
                        .HasName("pk_pedido_items");

                    b.HasIndex("CategoriaId")
                        .HasDatabaseName("ix_pedido_items_categoria_id");

                    b.HasIndex("PedidoId")
                        .HasDatabaseName("ix_pedido_items_pedido_id");

                    b.HasIndex("ProductoId")
                        .HasDatabaseName("ix_pedido_items_producto_id");

                    b.ToTable("pedido_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_pedido_items_cantidad", "cantidad > 0");
                        });
                });

            modelBuilder.Entity("Backend_Almacen.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer")
                        .HasColumnName("categoria_id");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("CreadoPorId")
                        .HasColumnType("integer")
                        .HasColumnName("creado_por");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("ImagenUrl")
                        .HasColumnType("text")
                        .HasColumnName("imagen_url");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("PrecioUsd")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("precio_usd");

                    b.Property<int>("StockDisponible")
                        .HasColumnType("integer")
                        .HasColumnName("stock_disponible");

                    b.Property<int>("StockReservado")
                        .HasColumnType("integer")
                        .HasColumnName("stock_reservado");

                    b.HasKey("Id")
                        .HasName("pk_productos");

                    b.HasIndex("CategoriaId")
                        .HasDatabaseName("ix_productos_categoria_id");

                    b.HasIndex("CreadoPorId")
                        .HasDatabaseName("ix_productos_creado_por_id");

                    b.ToTable("productos", null, t =>
                        {
                            t.HasCheckConstraint("ck_productos_precio_usd", "precio_usd >= 0");

                            t.HasCheckConstraint("ck_productos_stock_disponible", "stock_disponible >= 0");

                            t.HasCheckConstraint("ck_productos_stock_reservado", "stock_reservado >= 0");
                        });
                });

            modelBuilder.Entity("Backend_Almacen.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("GoogleId")
                        .HasColumnType("text")
                        .HasColumnName("google_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<RolUsuario>("Rol")
                        .HasColumnType("rol_usuario")
                        .HasColumnName("rol");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_email");

                    b.HasIndex("GoogleId")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_google_id");

                    b.ToTable("usuarios", null, t =>
                        {
                            t.HasCheckConstraint("ck_usuarios_credenciales", "(rol = 'cliente' AND google_id IS NOT NULL) OR (rol <> 'cliente' AND password_hash IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Backend_Almacen.Models.Zona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean")
                        .HasColumnName("activa");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_zonas");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ix_zonas_nombre");

                    b.ToTable("zonas", (string)null);
                });

            modelBuilder.Entity("Backend_Almacen.Models.Auditoria", b =>
                {
                    b.HasOne("Backend_Almacen.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_auditoria_usuarios_usuario_id");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Backend_Almacen.Models.HistorialEstadoPedido", b =>
                {
                    b.HasOne("Backend_Almacen.Models.Pedido", "Pedido")
                        .WithMany("HistorialEstados")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_historial_estados_pedido_pedidos_pedido_id");

                    b.HasOne("Backend_Almacen.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_historial_estados_pedido_usuarios_usuario_id");

                    b.Navigation("Pedido");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Backend_Almacen.Models.HistorialTasa", b =>
                {
                    b.HasOne("Backend_Almacen.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_historial_tasas_usuarios_usuario_id");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Backend_Almacen.Models.MensajeWhatsapp", b =>
                {
                    b.HasOne("Backend_Almacen.Models.Pedido", "Pedido")
                        .WithMany()
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_mensajes_whatsapp_pedidos_pedido_id");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("Backend_Almacen.Models.MovimientoInventario", b =>
                {
                    b.HasOne("Backend_Almacen.Models.Pedido", "Pedido")
                        .WithMany()
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_movimientos_inventario_pedidos_pedido_id");

                    b.HasOne("Backend_Almacen.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_movimientos_inventario_productos_producto_id");

                    b.HasOne("Backend_Almacen.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_movimientos_inventario_usuarios_usuario_id");

                    b.Navigation("Pedido");

                    b.Navigation("Producto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Backend_Almacen.Models.Notificacion", b =>
                {
                    b.HasOne("Backend_Almacen.Models.Pedido", "Pedido")
                        .WithMany()
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_notificaciones_pedidos_pedido_id");

                    b.HasOne("Backend_Almacen.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_notificaciones_productos_producto_id");

                    b.Navigation("Pedido");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Backend_Almacen.Models.Pedido", b =>
                {
                    b.HasOne("Backend_Almacen.Models.Usuario", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pedidos_usuarios_cliente_id");

                    b.HasOne("Backend_Almacen.Models.Usuario", "Repartidor")
                        .WithMany()
                        .HasForeignKey("RepartidorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_pedidos_usuarios_repartidor_id");

                    b.HasOne("Backend_Almacen.Models.Usuario", "RevisadoPor")
                        .WithMany()
                        .HasForeignKey("RevisadoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_pedidos_usuarios_revisado_por_id");

                    b.HasOne("Backend_Almacen.Models.Zona", "Zona")
                        .WithMany()
                        .HasForeignKey("ZonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pedidos_zonas_zona_id");

                    b.Navigation("Cliente");

                    b.Navigation("Repartidor");

                    b.Navigation("RevisadoPor");

                    b.Navigation("Zona");
                });

            modelBuilder.Entity("Backend_Almacen.Models.PedidoItem", b =>
                {
                    b.HasOne("Backend_Almacen.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pedido_items_categorias_categoria_id");

                    b.HasOne("Backend_Almacen.Models.Pedido", "Pedido")
                        .WithMany("Items")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pedido_items_pedidos_pedido_id");

                    b.HasOne("Backend_Almacen.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pedido_items_productos_producto_id");

                    b.Navigation("Categoria");

                    b.Navigation("Pedido");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Backend_Almacen.Models.Producto", b =>
                {
                    b.HasOne("Backend_Almacen.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_productos_categorias_categoria_id");

                    b.HasOne("Backend_Almacen.Models.Usuario", "CreadoPor")
                        .WithMany()
                        .HasForeignKey("CreadoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_productos_usuarios_creado_por_id");

                    b.Navigation("Categoria");

                    b.Navigation("CreadoPor");
                });

            modelBuilder.Entity("Backend_Almacen.Models.Pedido", b =>
                {
                    b.Navigation("HistorialEstados");

                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
