# ============================================================================
# Frontend_Almacen · Configuración de Nginx para la SPA
# ============================================================================

server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Redirigir todas las peticiones no encontradas a index.html
        # para soportar las rutas del cliente de React Router (SPA fallback).
        try_files $uri $uri/ /index.html;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
